[theme]
base = "light"
primaryColor = "#6c4ca8ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1F2937"

[server]
runOnSave = true
port = 8501
address = "0.0.0.0"
enableCORS = false
headless = true
